### ISSUE TITLE
Change basis, cell shape

### ISSUE THREAD

**Issue by lightislost** [unkcpz/pyyabc#7]
Te替换成Bi，Nb   都生成。 形状改变

O10Bi5
1
  0.000000  14.096250  14.096250
  2.819250   0.000000   2.819250
  2.819250   2.819250   0.000000
O Te
10 5
direct
  0.050000   0.250000   0.250000 O
  0.150000   0.750000   0.750000 O
  0.250000   0.250000   0.250000 O
  0.350000   0.750000   0.750000 O
  0.450000   0.250000   0.250000 O
  0.550000   0.750000   0.750000 O
  0.650000   0.250000   0.250000 O
  0.750000   0.750000   0.750000 O
  0.850000   0.250000   0.250000 O
  0.950000   0.750000   0.750000 O
  0.000000   0.000000   0.000000 Bi
  0.200000   0.000000   0.000000 Bi
  0.400000   0.000000   0.000000 Bi
  0.600000   0.000000   0.000000 Bi
  0.800000   0.000000   0.000000 Bi

**Comment by unkcpz** [comment]
贴一下cmd的命令，看一下是不是用的时候有错误。

**Comment by unkcpz** [comment]
zzcc no much problem
